### ISSUE TITLE
meteor bundle does not always work

### ISSUE THREAD

**Issue by mtmetra** [ardatan/meteor-webpack#18] opened 2018-05-12 20:33 UTC
After generating a meteor bundle using the command **meteor build**, the generated web uses to fail the first time I run the app in the browser. Then, after reloading the app pressing F5, the web works properly.
Every time I open a new web browser and load the bundle app, the described behaviour repeats (fails the first page load but after reload with F5 it works fine).
This behaviour has been observed in **Windows 10**, using the **react example**, both in **chrome** and **firefox**.
I have tried to run **set GALAXY_NODE_OPTIONS=--production** before running **meteor build**, but the problem remains the same.

**Comment by ardatan** [comment] 2018-05-12 22:08
First of all, thank you for your contribution.
`GALAXY_NODE_OPTIONS` is required for Galaxy deployment `meteor deploy`, it is not necessary for `meteor build` command.
Could you share more information such as console errors if exist etc?

**Comment by mtmetra** [comment] 2018-05-13 06:59
The console output is the following:

Uncaught ReferenceError: Package is not defined
    at Object.<anonymous> (main.js:1)
    at S (main.js:1)
    at r (main.js:1)
    at Object.<anonymous> (main.js:33)
    at S (main.js:1)
    at main.js:1
    at main.js:1

I attach also the main.js file (renamed to main.txt):
[main.txt](https://github.com/ardatan/meteor-webpack/files/1998200/main.txt)

**Comment by royGil** [comment] 2018-05-14 00:44
Arda, do you have an idea of why this is happening?

Also, what was the last version of this package that did manage to build successfully? maybe we can start there..

**Comment by ardatan** [comment] 2018-05-14 21:39
Your workaround shouldn't be the way of we use Meteor packages. I handled it via `defer` parameter.
https://github.com/ardatan/meteor-webpack/commit/4634bd87393f325fca846715a15fc3aa717f68b7#comments
You can check here, please try again and let me know if the problem still occurs.

**Comment by royGil** [comment] 2018-05-14 21:44
Didn't think about the "defer" parameter - well done!

And sure, I didn't propose it as a solution, just wanted to share that it's an order-loading problem..

**Comment by ardatan** [comment] 2018-05-14 21:45
@royGil Yes, it was great to remind me about `defer` parameters. Thanks a lot!

**Comment by mtmetra** [comment] 2018-05-15 05:41
Now the meteor build version works perfectly for the client.
Thank you very much.

**Comment by mtmetra** [comment] 2018-05-15 06:46
Excuse me, but...
Now (with version 0.0.5_1) the development version (meteor run) of the react example does not work.
I always get the following exception in the browser console:
`Uncaught ReferenceError: Package is not defined
    at eval (eval at meteor/meteor (app.js:1425), <anonymous>:1:18)
    at Object.meteor/meteor (app.js:1425)
    at __webpack_require__ (app.js:712)
    at fn (app.js:95)
    at Object.eval (App.jsx:19)
    at eval (App.jsx:189)
    at Object../client/ui/App.jsx (app.js:812)
    at __webpack_require__ (app.js:712)
    at fn (app.js:95)
    at eval (main.jsx:9)`

**Comment by mtmetra** [comment] 2018-05-16 05:44
The source code is just the one generated by the **react example** with **meteor run**.
The html rendered in the browser is:
[main.html.txt](https://github.com/ardatan/meteor-webpack/files/2007639/main.html.txt)
and the app.js is:
[app.js.txt](https://github.com/ardatan/meteor-webpack/files/2007640/app.js.txt)

**Comment by lnmunhoz** [comment] 2018-05-17 03:39
Hi @ardatan, got the same error here.
I've just ran the React example, and got `Package is not defined`.

**Comment by ardatan** [comment] 2018-05-17 04:12
Actually the thing is the execution order of the script. HtmlWebpackPlugin puts all bundles in index.html except meteor’s. However, we send that index.html but somehow Meteor puts its boilerplate at the end of the body. So, we are using a workaround to handle this by adding async parameter for each script tag. This doesn’t work on your environments. I am still working on this, I don’t want to make HtmlWebpackPlugin unsupported, because it is used a lot in webpack projects. So, if you have any idea please let me know. But first, I am going to fix examples to make everything works ( which is more important in the short term)

**Comment by lnmunhoz** [comment] 2018-05-17 05:07
@ardatan Sure will do! Thanks for replying.

Currently I'm trying to use in my project in production, and in the `main.js` file I am trying to:
```
import('meteor/meteor')
  .then(async () => {
    await import('./imports');
  });
```

But getting the same error with `Package`. Have any idea of a workaround?

**Comment by mtmetra** [comment] 2018-05-17 05:48
Now, with versión 0.0.5_3, the development version of the react example (meteor run) works fine, but the production version (meteor run --production) exhibits the same problems originally exposed in this issue: first load on browser does not work but succesive ones do work.

**Comment by ardatan** [comment] 2018-05-17 07:54
Finally! I found a solution about this async issue.
As the compiler gets `index.html` from webpack, it scans for `script` tags to collect scripts from there. Then, it sends these script to Meteor after removing these `script` element from `index.html`; and Meteor adds them after its scripts. This must solve your issue that I couldn't face so far :) However, it is possible because the browser might load them in different orders.
Please update packages, and let me know if anything changes.

**Comment by mtmetra** [comment] 2018-05-17 08:48
Now it works perfect, both development and production versions.
Thank you very much.

**Comment by ardatan** [comment] 2018-05-17 08:49
Finally, I found a solution about this async issue.
As the compiler gets index.html from webpack, it scans for script tags to collect scripts from there. Then, it sends these script to Meteor after removing these script element from index.html; and Meteor adds them after its scripts. This must solve your issue that I couldn't face so far :) However, it is possible because the browser might load them in different orders.
It'd better to work on automation tests @royGil! And we can setup Travis for this.

**Comment by ardatan** [comment] 2018-05-17 08:51
We can close the issue now 
Thanks for your contribution to make this project better 👍

**Closed by ardatan** 2018-05-17 08:51 UTC

**Comment by lnmunhoz** [comment] 2018-05-17 08:54
@ardatan I was having an issue where I depends on `FlowRouter` to load my routes, but the app was trying to access the route before anything, so I was getting `route not found` but right after that my routes were loaded.

I tried to wrap my imports Meteor.startup, but the issue continue, but looks like there's an initial load that is out of my control, so the app is starting before Meteor.startup, and then actually running it.

Any thoughts on that? I can create a repo reproducing this issue.

**Comment by ardatan** [comment] 2018-05-17 09:26
It will be perfect, if you reproduce a repo 👍

**Comment by lnmunhoz** [comment] 2018-05-17 10:12
@ardatan I've modified the react example so you can take a look :) https://github.com/lnmunhoz/meteor-webpack
